### ISSUE TITLE
Switch Epoch structure from 4-3-3 to 3-3-4 

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/ouroboros-consensus#297]
This is important for Genesis work. Ideally it should be done before Conway, however if it can be implemented in isolation within a single rule, then an intra-era hardfork could be possible as well.

Timeline for this is sometime next year (unclear when exactly).

Any questions about this should be directed to Christian Badertscher and Duncan

**Comment by nfrisby** [comment]
Also: Christian asked us to consider 4-2-4 which he said he would generally prefer of 3-3-4, if we don't have a significant preference.

**Comment by nfrisby** [comment]
We had to page this back into our brain today. I'm writing my summary here, since I struggled to recall it this clearly:

---

There are three phases of an epoch, in a ratio X:Y:Z.

X stake distribution stabilization
Y honest randomness
Z nonce stabilization

The implementation has only ever directly constrained X+Y+Z and Z.
Nothing in the implementation as ever constrained X or Y independently.

X+Y+Z has always been 10 -- specifically, the concrete length of an epoch is `10k/f` slots (ie 5 days of wall clock) --- so the ratio numbers hide a shared `k/f` constant.

The Praos->Genesis change (which we don't understand the motivation for) was to increase Z from 3 to 4.
Specifically before Conway it was 3 and in Conway it's now 4.

The confusing thing is that Z was always intended to be 4, but due to an early mistake is was 3.
Erratum 17.3 explains the mistake.
Thankfully using 3 instead of 4 was harmless during Praos, but needed to be fixed before Genesis.
