### ISSUE TITLE
Add hardfork logic support for Voltaire

### ISSUE THREAD

**Issue by dnadales** [IntersectMBO/ouroboros-consensus#61]
We should add harfork logic support for Voltaire. The new feature should be merged to `main`. This issue requires the following tasks:

- [ ] Specify what Voltaire governance actions are
    - This will allow us to understand to which actions consensus needs to react. We know we need at least to act on hardfork actions.
- [ ]  Specify (with the ledger team) how/if the ledger state needs to be inspected to decide governance actions.
    - Such a specification should land in a consensus design document.
- [ ] Understand and document how hard-forks are decided
    - We need to understand the current hardfork logic to understand what needs to be changed.
    - In particular, we need to understand what's the role of `proposalReachedQuorum`.
    - As a result of this activity we should improve our current documentation.
- [ ] Understand how [getProposedPPUpdates](https://github.com/input-output-hk/cardano-ledger/blob/c99488882e2231f2442d138ad6ec6e1809dc29c5/eras/shelley/impl/src/Cardano/Ledger/Shelley/Governance.hs#L57-L60) relates to the hardfork mechanics (in particular to `extendToSlot`).
- [ ] Look for tests that exercise `proposalReachedQuorum`.
    - We will need to test the new logic, hence the importance of this item. 
    - We might want to update the documentation.
- [ ] What is the relation between `votedValue` and `protocolUpdates.proposalReachedQuorum`?
   - Are they doing the same thing? Is `votedValue` or the result computed by this function used at all?
- [ ] Understand if there is any relation between `votedValue` and Consensus hard-fork logic.
    - ... or the field that `votedValue` affects, namely `futureProposals`.
- [ ] https://github.com/input-output-hk/ouroboros-consensus/issues/60

**Comment by JaredCorduan** [comment]
* The only governance action that consensus will need to care about, as far as I can tell, is the hard fork. I do not think that consensus cares about any of the other protocol parameters, and the other governance actions are definitively only ledger specific.
* If you look at CIP-1694, you'll see a distinction between a governance action being "ratified" and it being "enacted", where "ratified" means that the change is destined to happen, and enacted means the change has occurred. Ratification only happens on the epoch boundary, and hard forks that are ratified will be enacted on the following epoch boundary. In order to give the hard fork combinator the two stability windows that it requires, consensus will inspect the ledger state `4k/f`-many slots into the epoch and see if a hard fork has been ratified (the action will be removed upon enactment). In particular, it will inspect the new "CertState". The old "DPState" (consisting of the DState and the PState) has been renamed to "CertState" and now contains "VState", which has all the governance state.

**Comment by dnadales** [comment]
Closing this issue in favour of https://github.com/IntersectMBO/ouroboros-consensus/issues/920
