### ISSUE TITLE
Remove `HardForkEncoderDisabledEra` from NTN

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/ouroboros-consensus#873]
This Issue description is a stub. (See GitHub Comments below for elaboration.)

The footnote in the description of Issue https://github.com/IntersectMBO/ouroboros-network/issues/4770 suggests that `HardForkEncoderDisabledEra` is unnecessary. Moreover, it might be counterproductive: it seems more useful for the party who needs to update their code (to support the new era) to be the one whose codec fails, resulting in a log message indicating as much.

It's interesting that the opposite is true for NTC queries: we prefer the failure&log message on the encoder side, since they're encoding a value that the negotiated version disallows (ie they're buggy). Perhaps it's "always the client side", instead of "always the encoder"? Or maybe it's just that NTN payloads (headers, blocks, transactions) are outside the scope of the two connected parties (since they alone can't control the whole network's evolution) whereas the NTC payloads (ie queries and their responses) are fully determined by just these two parties.

Edit: I had initially thought `{Byron,Shelley,Cardano}NodeToNodeVersion*` were also unnecessary. However: the codec for headers (at least on-the-wire) is not solely determined by the protocol version. See eg `ByronNodeToNodeVersion1` vs `ByronNodeToNodeVersion2`. Indeed, even blocks and transactions have a degree of freedom between the over-the-wire codec and the storage codec (although one of them has to be chosen as canonical for the hashing).

**Comment by amesgen** [comment]
Nick and me chatted about this on Friday; based on that, I drafted a new issue description:

# Remove `EraNodeTo{Node,Client}Disabled`

Currently, the `BlockNodeTo{Node,Client}Version (HardForkBlock xs)` allows to individually disable eras[^disable-suffix] via `EraNodeTo{Node,Client}Version`:
https://github.com/IntersectMBO/ouroboros-consensus/blob/399f3dbe8c11ecb057f1cdb737092cea5e4b85c6/ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Serialisation/Common.hs#L189-L195

When en- or decoding an `NS xs`, the generic HFC serialization logic will throw an (imprecise) `HardForkEncoderDisabledEra` exception when the era corresponding to the index of the `NS xs` is disabled. This allows to guarantee that no communication takes place using entities in an era that is already supported by the code, but known not to be supported based on the negotiated protocol version.

There are a few motivations to change this mechanism:

 1. As this condition is enforced also on the encoder, it means that the "client" just sees everyone disconnecting from them, but no specific error message, which can be confusing in the node-to-node case.
    
    Concretely, consider two nodes `A` and `B` that negotiated a version where Conway is disabled, as `B` only supports Babbage and considers Conway experimental and hence disabled, in contrast to `A`, which is fine to HF to Conway. Now, when `A` forks to Conway, it will throw an exception when it tries to encode a Conway header to `B` and hence disconnect from `B`, with no direct for `B` knowing why this happened.

    In order to solve this specific issue, it would also be enough to simply enforce the disabled eras check in just the node-to-node decoder, but not in the node-to-node encoder.
 2. We already have an obsolete node check based on the *ledger* protocol version, see $\textsf{MaxMajorPV}$ in the Shelley ledger specs. It is not redundant, as the disabled eras mechanism can't account for intra-era HFs. It is weird to have two entirely different mechanisms to "disable" (in the sense of: "loud messages in the logs") eras.
   
    One slight advantage of the disabled eras mechanism is that it fails at an earlier stage, at the start of decoding, in contrast to ledger validation. A priori, it seems unlikely that this is an important factor. 
 3. It is arguably too expressive, see #587. In particular, closing this issue would also close #587.

The goal of this issue is to remove the disabled eras mechanism (such that the constructors `EraNodeTo{Node,Client}Disabled`) no longer exist, and ensure that the obsolete node check (mentioned in 2.) is configured in such a way that it fully supersedes it.

**Comment by nfrisby** [comment]
I prototyped pushing this deletion through `cabal build all` tonight. When I started tidying up the `CardanoNodeToClientX` pattern synonyms, it made me realize: I think we need to keep `EraNodeToClientDisabled`, and only remove `EraNodeToNodeDisabled`, at least for now.

There are the types of HFC query: `QueryIfCurrent`, `QueryAnytime`, and `QueryHardFork`. The `QueryHardFork` query is agnostic to which queries exist. And the result types of the other two would permit the node to respond soundly to a query about an era it doesn't even know about. However, the `QueryIfCurrent` and `QueryAnytime` queries currently could not even be decoded for such an era. Thus, unless we reify that case into an HFC query constructor that so the decoder needn't fail, we should preserve `EraNodeToClientDisabled` so that the client side sees the encoder failure instead, instead of the node seeing the decoder failure.

To be clear: all the reasoning before this GitHub comment does still apply to `EraNodeToNodeDisabled`, just not `EraNodeToClientDisabled`.

**Comment by amesgen** [comment]
Hmm, can't the client just send

**Comment by nfrisby** [comment]
> a client can always first send a `QueryHardFork GetCurrentEra` after it acquired a ledger state to find out what era it is in. 

Yeah, that's true. But I'd say it contradicts the Networking Team's root goal of "the negotiated version completely determines which codecs to use for the lifetime of the connection".

**Comment by amesgen** [comment]
> But I'd say it contradicts the Networking Team's root goal of "the negotiated version completely determines which codecs to use for the lifetime of the connection".

Hmm, I don't really have an intuition whether the version check is indeed morally part of the en/decoder or if it is rather just a convenient place to do this version check in the current code, but not really related to en/decoding (in contrast to actual changes in the CBOR).

**Comment by nfrisby** [comment]
PR #913 leaves the NTC side in the code. We can open a new Issue to reconsider how to also remove that (eg requiring `GetCurrentEra`), if you think that's worthwhile? Might require negotiation with Networking Team architects, eg.
